_ := print_endline (string_cat A."Current directory name: " (filenm_get_current_dir_name A.()));
_ := print_endline (string_cat A."Parent directory name: " (filenm_get_parent_dir_name A.()));
_ := print_endline (string_cat A."System directory seperator: " (filenm_get_dir_sep A.()));
_ := print_endline (string_cat A."CWD: " (sys_get_cwd A.()));
_ := print_endline (string_cat A."Is CWD a relative path?: " (string_of_bool (filenm_is_relative_filepath (sys_get_cwd A.()))));
_ := print_endline (string_cat A."Basename from CWD: " (filenm_get_basename_from_path (sys_get_cwd A.())));
_ := print_endline (string_cat A."Dirname from CWD: " (filenm_get_dirname_from_path (sys_get_cwd A.())));
_ := print_endline (string_cat A."Current Pirouette file: " (string_cat (string_cat (sys_get_cwd A.()) (filenm_get_dir_sep A.())) A."filenm.pir"));
_ := print_endline (string_cat A."Extension from current Pirouette file: " (filenm_get_file_extension (string_cat (string_cat (sys_get_cwd A.()) (filenm_get_dir_sep A.())) A."filenm.pir")));